import './styles.css'

export const metadata = {
	description: 'Generated by Create Rubric App',
	title: 'Create Rubric App'
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang="en">
			<body>{children}</body>
		</html>
	)
}
